"""Suspend watcher

Revision ID: 35654106913f
Revises: 62204037fe4f
Create Date: 2024-04-29 17:42:34.215299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35654106913f'
down_revision: Union[str, None] = '62204037fe4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_watch_suspensions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('watch_type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('suspended_until', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_watch_suspensions_id'), 'site_watch_suspensions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_watch_suspensions_id'), table_name='site_watch_suspensions')
    op.drop_table('site_watch_suspensions')
    # ### end Alembic commands ###
